package io.nekohasekai.sfa.compose.util

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.*
import androidx.compose.material.icons.filled.*
import androidx.compose.material.icons.outlined.*
import androidx.compose.material.icons.rounded.*
import androidx.compose.material.icons.sharp.*
import androidx.compose.material.icons.twotone.*
import androidx.compose.ui.graphics.vector.ImageVector

data class IconCategory(val name: String, val icons: List<ProfileIcon>)

object MaterialIconsLibrary {
    val categories =
        listOf(
            IconCategory(
                "Security & Privacy",
                listOf(
                    ProfileIcon("shield", Icons.Filled.Shield, "Shield"),
                    ProfileIcon("security", Icons.Filled.Security, "Security"),
                    ProfileIcon("lock", Icons.Filled.Lock, "Lock"),
                    ProfileIcon("lock_open", Icons.Filled.LockOpen, "Lock Open"),
                    ProfileIcon("vpn_key", Icons.Filled.VpnKey, "VPN Key"),
                    ProfileIcon("vpn_lock", Icons.Filled.VpnLock, "VPN Lock"),
                    ProfileIcon("key", Icons.Filled.Key, "Key"),
                    ProfileIcon("password", Icons.Filled.Password, "Password"),
                    ProfileIcon("fingerprint", Icons.Filled.Fingerprint, "Fingerprint"),
                    ProfileIcon("verified_user", Icons.Filled.VerifiedUser, "Verified"),
                    ProfileIcon("privacy_tip", Icons.Filled.PrivacyTip, "Privacy"),
                    ProfileIcon("admin_panel", Icons.Filled.AdminPanelSettings, "Admin"),
                    ProfileIcon("policy", Icons.Filled.Policy, "Policy"),
                    ProfileIcon("gpp_good", Icons.Filled.GppGood, "Protected"),
                    ProfileIcon("gpp_maybe", Icons.Filled.GppMaybe, "Maybe Protected"),
                    ProfileIcon("enhanced_encryption", Icons.Filled.EnhancedEncryption, "Encryption"),
                    ProfileIcon("no_encryption", Icons.Filled.NoEncryption, "No Encryption"),
                    ProfileIcon("https", Icons.Filled.Https, "HTTPS"),
                    ProfileIcon("http", Icons.Filled.Http, "HTTP"),
                    ProfileIcon("safety_check", Icons.Filled.SafetyCheck, "Safety Check"),
                ),
            ),
            IconCategory(
                "Network & Connection",
                listOf(
                    ProfileIcon("wifi", Icons.Filled.Wifi, "WiFi"),
                    ProfileIcon("wifi_off", Icons.Filled.WifiOff, "WiFi Off"),
                    ProfileIcon("wifi_lock", Icons.Filled.WifiLock, "WiFi Lock"),
                    ProfileIcon("wifi_tethering", Icons.Filled.WifiTethering, "Tethering"),
                    ProfileIcon("signal_wifi_4_bar", Icons.Filled.SignalWifi4Bar, "Strong WiFi"),
                    ProfileIcon("signal_wifi_bad", Icons.Filled.SignalWifiBad, "Bad WiFi"),
                    ProfileIcon("router", Icons.Filled.Router, "Router"),
                    ProfileIcon("network_check", Icons.Filled.NetworkCheck, "Network Check"),
                    ProfileIcon("network_locked", Icons.Filled.NetworkLocked, "Network Locked"),
                    ProfileIcon("network_ping", Icons.Filled.NetworkPing, "Network Ping"),
                    ProfileIcon("hub", Icons.Filled.Hub, "Hub"),
                    ProfileIcon("dns", Icons.Filled.Dns, "DNS"),
                    ProfileIcon("lan", Icons.Filled.Lan, "LAN"),
                    ProfileIcon("cable", Icons.Filled.Cable, "Cable"),
                    ProfileIcon("settings_ethernet", Icons.Filled.SettingsEthernet, "Ethernet"),
                    ProfileIcon("cell_tower", Icons.Filled.CellTower, "Cell Tower"),
                    ProfileIcon("cell_wifi", Icons.Filled.CellWifi, "Cell WiFi"),
                    ProfileIcon("signal_cellular_4_bar", Icons.Filled.SignalCellular4Bar, "4G"),
                    ProfileIcon("signal_cellular_alt", Icons.Filled.SignalCellularAlt, "Cellular"),
                    // Some newer icons might not be available in all versions
                    // ProfileIcon("5g", Icons.Filled.FiveG, "5G"),
                    // ProfileIcon("4g_mobiledata", Icons.Filled.FourGMobiledata, "4G"),
                    // ProfileIcon("lte_mobiledata", Icons.Filled.LteMobiledata, "LTE")
                ),
            ),
            IconCategory(
                "Global & Cloud",
                listOf(
                    ProfileIcon("language", Icons.Filled.Language, "Globe"),
                    ProfileIcon("public", Icons.Filled.Public, "Public"),
                    ProfileIcon("public_off", Icons.Filled.PublicOff, "Public Off"),
                    ProfileIcon("travel_explore", Icons.Filled.TravelExplore, "Explore"),
                    ProfileIcon("cloud", Icons.Filled.Cloud, "Cloud"),
                    ProfileIcon("cloud_upload", Icons.Filled.CloudUpload, "Cloud Upload"),
                    ProfileIcon("cloud_download", Icons.Filled.CloudDownload, "Cloud Download"),
                    ProfileIcon("cloud_sync", Icons.Filled.CloudSync, "Cloud Sync"),
                    ProfileIcon("cloud_done", Icons.Filled.CloudDone, "Cloud Done"),
                    ProfileIcon("cloud_off", Icons.Filled.CloudOff, "Cloud Off"),
                    ProfileIcon("cloud_queue", Icons.Filled.CloudQueue, "Cloud Queue"),
                    ProfileIcon("backup", Icons.Filled.Backup, "Backup"),
                    ProfileIcon("satellite", Icons.Filled.Satellite, "Satellite"),
                    ProfileIcon("satellite_alt", Icons.Filled.SatelliteAlt, "Satellite Alt"),
                    ProfileIcon("share", Icons.Filled.Share, "Share"),
                    ProfileIcon("share_location", Icons.Filled.ShareLocation, "Share Location"),
                    ProfileIcon("sync", Icons.Filled.Sync, "Sync"),
                    ProfileIcon("sync_alt", Icons.Filled.SyncAlt, "Sync Alt"),
                ),
            ),
            IconCategory(
                "Devices",
                listOf(
                    ProfileIcon("computer", Icons.Filled.Computer, "Computer"),
                    ProfileIcon("desktop_windows", Icons.Filled.DesktopWindows, "Desktop"),
                    ProfileIcon("laptop", Icons.Filled.Laptop, "Laptop"),
                    ProfileIcon("laptop_chromebook", Icons.Filled.LaptopChromebook, "Chromebook"),
                    ProfileIcon("laptop_mac", Icons.Filled.LaptopMac, "MacBook"),
                    ProfileIcon("laptop_windows", Icons.Filled.LaptopWindows, "Windows Laptop"),
                    ProfileIcon("smartphone", Icons.Filled.Smartphone, "Phone"),
                    ProfileIcon("phone_android", Icons.Filled.PhoneAndroid, "Android"),
                    ProfileIcon("phone_iphone", Icons.Filled.PhoneIphone, "iPhone"),
                    ProfileIcon("tablet", Icons.Filled.Tablet, "Tablet"),
                    ProfileIcon("tablet_android", Icons.Filled.TabletAndroid, "Android Tablet"),
                    ProfileIcon("tablet_mac", Icons.Filled.TabletMac, "iPad"),
                    ProfileIcon("watch", Icons.Filled.Watch, "Watch"),
                    ProfileIcon("tv", Icons.Filled.Tv, "TV"),
                    ProfileIcon("smart_display", Icons.Filled.SmartDisplay, "Smart Display"),
                    ProfileIcon("speaker", Icons.Filled.Speaker, "Speaker"),
                    ProfileIcon("headphones", Icons.Filled.Headphones, "Headphones"),
                    ProfileIcon("devices", Icons.Filled.Devices, "Devices"),
                    ProfileIcon("device_hub", Icons.Filled.DeviceHub, "Device Hub"),
                    ProfileIcon("cast", Icons.Filled.Cast, "Cast"),
                    ProfileIcon("cast_connected", Icons.Filled.CastConnected, "Cast Connected"),
                ),
            ),
            IconCategory(
                "Places & Activities",
                listOf(
                    ProfileIcon("home", Icons.Filled.Home, "Home"),
                    ProfileIcon("house", Icons.Filled.House, "House"),
                    ProfileIcon("cabin", Icons.Filled.Cabin, "Cabin"),
                    ProfileIcon("apartment", Icons.Filled.Apartment, "Apartment"),
                    ProfileIcon("work", Icons.Filled.Work, "Work"),
                    ProfileIcon("work_outline", Icons.Outlined.Work, "Work Outline"),
                    ProfileIcon("business", Icons.Filled.Business, "Business"),
                    ProfileIcon("business_center", Icons.Filled.BusinessCenter, "Business Center"),
                    ProfileIcon("school", Icons.Filled.School, "School"),
                    ProfileIcon("local_library", Icons.Filled.LocalLibrary, "Library"),
                    ProfileIcon("store", Icons.Filled.Store, "Store"),
                    ProfileIcon("storefront", Icons.Filled.Storefront, "Storefront"),
                    ProfileIcon("restaurant", Icons.Filled.Restaurant, "Restaurant"),
                    ProfileIcon("coffee", Icons.Filled.Coffee, "Coffee"),
                    ProfileIcon("local_cafe", Icons.Filled.LocalCafe, "Cafe"),
                    ProfileIcon("hotel", Icons.Filled.Hotel, "Hotel"),
                    ProfileIcon("flight", Icons.Filled.Flight, "Flight"),
                    ProfileIcon("flight_takeoff", Icons.Filled.FlightTakeoff, "Takeoff"),
                    ProfileIcon("flight_land", Icons.Filled.FlightLand, "Landing"),
                    ProfileIcon("train", Icons.Filled.Train, "Train"),
                    ProfileIcon("directions_car", Icons.Filled.DirectionsCar, "Car"),
                    ProfileIcon("directions_bus", Icons.Filled.DirectionsBus, "Bus"),
                    ProfileIcon("directions_subway", Icons.Filled.DirectionsSubway, "Subway"),
                    ProfileIcon("beach_access", Icons.Filled.BeachAccess, "Beach"),
                    ProfileIcon("park", Icons.Filled.Park, "Park"),
                    ProfileIcon("fitness_center", Icons.Filled.FitnessCenter, "Gym"),
                    ProfileIcon("sports_esports", Icons.Filled.SportsEsports, "Gaming"),
                    ProfileIcon("stadium", Icons.Filled.Stadium, "Stadium"),
                ),
            ),
            IconCategory(
                "Communication",
                listOf(
                    ProfileIcon("email", Icons.Filled.Email, "Email"),
                    ProfileIcon("mail", Icons.Filled.Mail, "Mail"),
                    ProfileIcon("message", Icons.Filled.Message, "Message"),
                    ProfileIcon("chat", Icons.Filled.Chat, "Chat"),
                    ProfileIcon("chat_bubble", Icons.Filled.ChatBubble, "Chat Bubble"),
                    ProfileIcon("forum", Icons.Filled.Forum, "Forum"),
                    ProfileIcon("comment", Icons.Filled.Comment, "Comment"),
                    ProfileIcon("call", Icons.Filled.Call, "Call"),
                    ProfileIcon("video_call", Icons.Filled.VideoCall, "Video Call"),
                    ProfileIcon("contacts", Icons.Filled.Contacts, "Contacts"),
                    ProfileIcon("contact_mail", Icons.Filled.ContactMail, "Contact Mail"),
                    ProfileIcon("contact_phone", Icons.Filled.ContactPhone, "Contact Phone"),
                    ProfileIcon("notifications", Icons.Filled.Notifications, "Notifications"),
                    ProfileIcon("notifications_active", Icons.Filled.NotificationsActive, "Active Notif"),
                    ProfileIcon("notification_important", Icons.Filled.NotificationImportant, "Important"),
                    ProfileIcon("announcement", Icons.Filled.Announcement, "Announcement"),
                ),
            ),
            IconCategory(
                "Media & Entertainment",
                listOf(
                    ProfileIcon("play_arrow", Icons.Filled.PlayArrow, "Play"),
                    ProfileIcon("play_circle", Icons.Filled.PlayCircle, "Play Circle"),
                    ProfileIcon("pause", Icons.Filled.Pause, "Pause"),
                    ProfileIcon("pause_circle", Icons.Filled.PauseCircle, "Pause Circle"),
                    ProfileIcon("stop", Icons.Filled.Stop, "Stop"),
                    ProfileIcon("skip_next", Icons.Filled.SkipNext, "Next"),
                    ProfileIcon("skip_previous", Icons.Filled.SkipPrevious, "Previous"),
                    ProfileIcon("music_note", Icons.Filled.MusicNote, "Music"),
                    ProfileIcon("audiotrack", Icons.Filled.Audiotrack, "Audio"),
                    ProfileIcon("album", Icons.Filled.Album, "Album"),
                    ProfileIcon("mic", Icons.Filled.Mic, "Microphone"),
                    ProfileIcon("videocam", Icons.Filled.Videocam, "Video"),
                    ProfileIcon("movie", Icons.Filled.Movie, "Movie"),
                    ProfileIcon("theaters", Icons.Filled.Theaters, "Theater"),
                    ProfileIcon("live_tv", Icons.Filled.LiveTv, "Live TV"),
                    ProfileIcon("photo", Icons.Filled.Photo, "Photo"),
                    ProfileIcon("photo_camera", Icons.Filled.PhotoCamera, "Camera"),
                    ProfileIcon("photo_library", Icons.Filled.PhotoLibrary, "Gallery"),
                    ProfileIcon("games", Icons.Filled.Games, "Games"),
                    ProfileIcon("sports_soccer", Icons.Filled.SportsSoccer, "Soccer"),
                    ProfileIcon("sports_basketball", Icons.Filled.SportsBasketball, "Basketball"),
                    ProfileIcon("sports_football", Icons.Filled.SportsFootball, "Football"),
                ),
            ),
            IconCategory(
                "Files & Folders",
                listOf(
                    ProfileIcon("folder", Icons.Filled.Folder, "Folder"),
                    ProfileIcon("folder_open", Icons.Filled.FolderOpen, "Folder Open"),
                    ProfileIcon("folder_shared", Icons.Filled.FolderShared, "Shared Folder"),
                    ProfileIcon("folder_special", Icons.Filled.FolderSpecial, "Special Folder"),
                    ProfileIcon("create_new_folder", Icons.Filled.CreateNewFolder, "New Folder"),
                    ProfileIcon("insert_drive_file", Icons.AutoMirrored.Filled.InsertDriveFile, "File"),
                    ProfileIcon("description", Icons.Filled.Description, "Document"),
                    ProfileIcon("article", Icons.AutoMirrored.Filled.Article, "Article"),
                    ProfileIcon("picture_as_pdf", Icons.Filled.PictureAsPdf, "PDF"),
                    ProfileIcon("attach_file", Icons.Filled.AttachFile, "Attachment"),
                    ProfileIcon("file_download", Icons.Filled.FileDownload, "Download"),
                    ProfileIcon("file_upload", Icons.Filled.FileUpload, "Upload"),
                    ProfileIcon("file_copy", Icons.Filled.FileCopy, "Copy"),
                    ProfileIcon("content_copy", Icons.Filled.ContentCopy, "Copy Content"),
                    ProfileIcon("content_paste", Icons.Filled.ContentPaste, "Paste"),
                    ProfileIcon("save", Icons.Filled.Save, "Save"),
                    ProfileIcon("save_alt", Icons.Filled.SaveAlt, "Save Alt"),
                    ProfileIcon("archive", Icons.Filled.Archive, "Archive"),
                    ProfileIcon("inventory", Icons.Filled.Inventory, "Inventory"),
                    ProfileIcon("storage", Icons.Filled.Storage, "Storage"),
                ),
            ),
            IconCategory(
                "Actions & Tools",
                listOf(
                    ProfileIcon("settings", Icons.Filled.Settings, "Settings"),
                    ProfileIcon("build", Icons.Filled.Build, "Build"),
                    ProfileIcon("extension", Icons.Filled.Extension, "Extension"),
                    ProfileIcon("search", Icons.Filled.Search, "Search"),
                    ProfileIcon("zoom_in", Icons.Filled.ZoomIn, "Zoom In"),
                    ProfileIcon("zoom_out", Icons.Filled.ZoomOut, "Zoom Out"),
                    ProfileIcon("info", Icons.Filled.Info, "Info"),
                    ProfileIcon("help", Icons.Filled.Help, "Help"),
                    ProfileIcon("help_center", Icons.Filled.HelpCenter, "Help Center"),
                    ProfileIcon("explore", Icons.Filled.Explore, "Explore"),
                    ProfileIcon("bookmark", Icons.Filled.Bookmark, "Bookmark"),
                    ProfileIcon("bookmarks", Icons.Filled.Bookmarks, "Bookmarks"),
                    ProfileIcon("history", Icons.Filled.History, "History"),
                    ProfileIcon("schedule", Icons.Filled.Schedule, "Schedule"),
                    ProfileIcon("alarm", Icons.Filled.Alarm, "Alarm"),
                    ProfileIcon("timer", Icons.Filled.Timer, "Timer"),
                    ProfileIcon("update", Icons.Filled.Update, "Update"),
                    ProfileIcon("upgrade", Icons.Filled.Upgrade, "Upgrade"),
                    ProfileIcon("autorenew", Icons.Filled.Autorenew, "Auto Renew"),
                    ProfileIcon("cached", Icons.Filled.Cached, "Cached"),
                    ProfileIcon("refresh", Icons.Filled.Refresh, "Refresh"),
                    ProfileIcon("sync_problem", Icons.Filled.SyncProblem, "Sync Problem"),
                    ProfileIcon("download", Icons.Filled.Download, "Download"),
                    ProfileIcon("upload", Icons.Filled.Upload, "Upload"),
                    ProfileIcon("print", Icons.Filled.Print, "Print"),
                    ProfileIcon("delete", Icons.Filled.Delete, "Delete"),
                ),
            ),
            IconCategory(
                "Status & Indicators",
                listOf(
                    ProfileIcon("check", Icons.Filled.Check, "Check"),
                    ProfileIcon("check_circle", Icons.Filled.CheckCircle, "Check Circle"),
                    ProfileIcon("verified", Icons.Filled.Verified, "Verified"),
                    ProfileIcon("done", Icons.Filled.Done, "Done"),
                    ProfileIcon("done_all", Icons.Filled.DoneAll, "Done All"),
                    ProfileIcon("close", Icons.Filled.Close, "Close"),
                    ProfileIcon("cancel", Icons.Filled.Cancel, "Cancel"),
                    ProfileIcon("error", Icons.Filled.Error, "Error"),
                    ProfileIcon("warning", Icons.Filled.Warning, "Warning"),
                    ProfileIcon("report", Icons.Filled.Report, "Report"),
                    ProfileIcon("flag", Icons.Filled.Flag, "Flag"),
                    ProfileIcon("star", Icons.Filled.Star, "Star"),
                    ProfileIcon("star_half", Icons.Filled.StarHalf, "Half Star"),
                    ProfileIcon("star_outline", Icons.Filled.StarOutline, "Star Outline"),
                    ProfileIcon("favorite", Icons.Filled.Favorite, "Favorite"),
                    ProfileIcon("favorite_border", Icons.Filled.FavoriteBorder, "Favorite Border"),
                    ProfileIcon("thumb_up", Icons.Filled.ThumbUp, "Like"),
                    ProfileIcon("thumb_down", Icons.Filled.ThumbDown, "Dislike"),
                    ProfileIcon("priority_high", Icons.Filled.PriorityHigh, "High Priority"),
                    ProfileIcon("new_releases", Icons.Filled.NewReleases, "New"),
                    ProfileIcon("fiber_new", Icons.Filled.FiberNew, "New Badge"),
                    ProfileIcon("offline_pin", Icons.Filled.OfflinePin, "Offline"),
                    ProfileIcon("online_prediction", Icons.Filled.OnlinePrediction, "Online"),
                ),
            ),
            IconCategory(
                "Nature & Weather",
                listOf(
                    ProfileIcon("wb_sunny", Icons.Filled.WbSunny, "Sunny"),
                    ProfileIcon("nights_stay", Icons.Filled.NightsStay, "Night"),
                    ProfileIcon("brightness_high", Icons.Filled.BrightnessHigh, "Bright"),
                    ProfileIcon("wb_cloudy", Icons.Filled.WbCloudy, "Cloudy"),
                    ProfileIcon("cloud", Icons.Filled.Cloud, "Cloud"),
                    ProfileIcon("ac_unit", Icons.Filled.AcUnit, "Snow"),
                    ProfileIcon("thunderstorm", Icons.Filled.Thunderstorm, "Storm"),
                    ProfileIcon("water_drop", Icons.Filled.WaterDrop, "Water"),
                    ProfileIcon("waves", Icons.Filled.Waves, "Waves"),
                    ProfileIcon("eco", Icons.Filled.Eco, "Eco"),
                    ProfileIcon("nature", Icons.Filled.Nature, "Nature"),
                    ProfileIcon("nature_people", Icons.Filled.NaturePeople, "Nature People"),
                    ProfileIcon("forest", Icons.Filled.Forest, "Forest"),
                    ProfileIcon("grass", Icons.Filled.Grass, "Grass"),
                    ProfileIcon("local_florist", Icons.Filled.LocalFlorist, "Flower"),
                    ProfileIcon("pets", Icons.Filled.Pets, "Pets"),
                    ProfileIcon("bug_report", Icons.Filled.BugReport, "Bug"),
                    ProfileIcon("spa", Icons.Filled.Spa, "Spa"),
                    ProfileIcon("pool", Icons.Filled.Pool, "Pool"),
                    ProfileIcon("hot_tub", Icons.Filled.HotTub, "Hot Tub"),
                ),
            ),
            IconCategory(
                "Transportation",
                listOf(
                    ProfileIcon("local_shipping", Icons.Filled.LocalShipping, "Shipping"),
                    ProfileIcon("local_taxi", Icons.Filled.LocalTaxi, "Taxi"),
                    ProfileIcon("directions_bike", Icons.Filled.DirectionsBike, "Bike"),
                    ProfileIcon("directions_boat", Icons.Filled.DirectionsBoat, "Boat"),
                    ProfileIcon("directions_railway", Icons.Filled.DirectionsRailway, "Railway"),
                    ProfileIcon("directions_transit", Icons.Filled.DirectionsTransit, "Transit"),
                    ProfileIcon("directions_walk", Icons.Filled.DirectionsWalk, "Walk"),
                    ProfileIcon("directions_run", Icons.Filled.DirectionsRun, "Run"),
                    ProfileIcon("electric_car", Icons.Filled.ElectricCar, "Electric Car"),
                    ProfileIcon("electric_bike", Icons.Filled.ElectricBike, "E-Bike"),
                    ProfileIcon("electric_scooter", Icons.Filled.ElectricScooter, "E-Scooter"),
                    ProfileIcon("two_wheeler", Icons.Filled.TwoWheeler, "Two Wheeler"),
                    ProfileIcon("motorcycle", Icons.Filled.Motorcycle, "Motorcycle"),
                    ProfileIcon("airport_shuttle", Icons.Filled.AirportShuttle, "Shuttle"),
                    ProfileIcon("commute", Icons.Filled.Commute, "Commute"),
                    ProfileIcon("rocket", Icons.Filled.Rocket, "Rocket"),
                    ProfileIcon("rocket_launch", Icons.Filled.RocketLaunch, "Rocket Launch"),
                    ProfileIcon("sailing", Icons.Filled.Sailing, "Sailing"),
                ),
            ),
            IconCategory(
                "Shopping & Finance",
                listOf(
                    ProfileIcon("shopping_cart", Icons.Filled.ShoppingCart, "Cart"),
                    ProfileIcon("shopping_bag", Icons.Filled.ShoppingBag, "Shopping Bag"),
                    ProfileIcon("shopping_basket", Icons.Filled.ShoppingBasket, "Basket"),
                    ProfileIcon("add_shopping_cart", Icons.Filled.AddShoppingCart, "Add to Cart"),
                    ProfileIcon("local_mall", Icons.Filled.LocalMall, "Mall"),
                    ProfileIcon("local_grocery_store", Icons.Filled.LocalGroceryStore, "Grocery"),
                    ProfileIcon("payment", Icons.Filled.Payment, "Payment"),
                    ProfileIcon("credit_card", Icons.Filled.CreditCard, "Credit Card"),
                    ProfileIcon("account_balance", Icons.Filled.AccountBalance, "Bank"),
                    ProfileIcon("account_balance_wallet", Icons.Filled.AccountBalanceWallet, "Wallet"),
                    ProfileIcon("wallet", Icons.Filled.Wallet, "Wallet"),
                    ProfileIcon("savings", Icons.Filled.Savings, "Savings"),
                    ProfileIcon("attach_money", Icons.Filled.AttachMoney, "Money"),
                    ProfileIcon("money", Icons.Filled.Money, "Cash"),
                    ProfileIcon("paid", Icons.Filled.Paid, "Paid"),
                    ProfileIcon("currency_bitcoin", Icons.Filled.CurrencyBitcoin, "Bitcoin"),
                    ProfileIcon("currency_exchange", Icons.Filled.CurrencyExchange, "Exchange"),
                    ProfileIcon("receipt", Icons.Filled.Receipt, "Receipt"),
                    ProfileIcon("receipt_long", Icons.Filled.ReceiptLong, "Receipt Long"),
                    ProfileIcon("sell", Icons.Filled.Sell, "Sell"),
                    ProfileIcon("discount", Icons.Filled.Discount, "Discount"),
                    ProfileIcon("redeem", Icons.Filled.Redeem, "Redeem"),
                ),
            ),
            IconCategory(
                "Health & Wellness",
                listOf(
                    ProfileIcon("medical_services", Icons.Filled.MedicalServices, "Medical"),
                    ProfileIcon("medication", Icons.Filled.Medication, "Medication"),
                    ProfileIcon("vaccines", Icons.Filled.Vaccines, "Vaccine"),
                    ProfileIcon("healing", Icons.Filled.Healing, "Healing"),
                    ProfileIcon("health_and_safety", Icons.Filled.HealthAndSafety, "Health & Safety"),
                    ProfileIcon("local_hospital", Icons.Filled.LocalHospital, "Hospital"),
                    ProfileIcon("local_pharmacy", Icons.Filled.LocalPharmacy, "Pharmacy"),
                    ProfileIcon("monitor_heart", Icons.Filled.MonitorHeart, "Heart Monitor"),
                    ProfileIcon("bloodtype", Icons.Filled.Bloodtype, "Blood Type"),
                    ProfileIcon("emergency", Icons.Filled.Emergency, "Emergency"),
                    ProfileIcon("medical_information", Icons.Filled.MedicalInformation, "Medical Info"),
                    ProfileIcon("psychology", Icons.Filled.Psychology, "Psychology"),
                    ProfileIcon("self_improvement", Icons.Filled.SelfImprovement, "Self Improvement"),
                    ProfileIcon("mood", Icons.Filled.Mood, "Happy"),
                    ProfileIcon("mood_bad", Icons.Filled.MoodBad, "Sad"),
                    ProfileIcon("sentiment_satisfied", Icons.Filled.SentimentSatisfied, "Satisfied"),
                    ProfileIcon("sentiment_dissatisfied", Icons.Filled.SentimentDissatisfied, "Dissatisfied"),
                    ProfileIcon("sick", Icons.Filled.Sick, "Sick"),
                    ProfileIcon("masks", Icons.Filled.Masks, "Masks"),
                    ProfileIcon("sanitizer", Icons.Filled.Sanitizer, "Sanitizer"),
                    ProfileIcon("clean_hands", Icons.Filled.CleanHands, "Clean Hands"),
                    ProfileIcon("coronavirus", Icons.Filled.Coronavirus, "Virus"),
                ),
            ),
            IconCategory(
                "Food & Dining",
                listOf(
                    ProfileIcon("restaurant_menu", Icons.Filled.RestaurantMenu, "Menu"),
                    ProfileIcon("fastfood", Icons.Filled.Fastfood, "Fast Food"),
                    ProfileIcon("lunch_dining", Icons.Filled.LunchDining, "Lunch"),
                    ProfileIcon("dinner_dining", Icons.Filled.DinnerDining, "Dinner"),
                    ProfileIcon("breakfast_dining", Icons.Filled.BreakfastDining, "Breakfast"),
                    ProfileIcon("brunch_dining", Icons.Filled.BrunchDining, "Brunch"),
                    ProfileIcon("bakery_dining", Icons.Filled.BakeryDining, "Bakery"),
                    ProfileIcon("icecream", Icons.Filled.Icecream, "Ice Cream"),
                    ProfileIcon("cake", Icons.Filled.Cake, "Cake"),
                    ProfileIcon("local_pizza", Icons.Filled.LocalPizza, "Pizza"),
                    ProfileIcon("local_bar", Icons.Filled.LocalBar, "Bar"),
                    ProfileIcon("local_drink", Icons.Filled.LocalDrink, "Drink"),
                    ProfileIcon("liquor", Icons.Filled.Liquor, "Liquor"),
                    ProfileIcon("wine_bar", Icons.Filled.WineBar, "Wine"),
                    ProfileIcon("sports_bar", Icons.Filled.SportsBar, "Sports Bar"),
                    ProfileIcon("kitchen", Icons.Filled.Kitchen, "Kitchen"),
                    ProfileIcon("dining", Icons.Filled.Dining, "Dining"),
                    ProfileIcon("food_bank", Icons.Filled.FoodBank, "Food Bank"),
                    ProfileIcon("ramen_dining", Icons.Filled.RamenDining, "Ramen"),
                    ProfileIcon("rice_bowl", Icons.Filled.RiceBowl, "Rice Bowl"),
                    ProfileIcon("soup_kitchen", Icons.Filled.SoupKitchen, "Soup"),
                    ProfileIcon("takeout_dining", Icons.Filled.TakeoutDining, "Takeout"),
                    ProfileIcon("delivery_dining", Icons.Filled.DeliveryDining, "Delivery"),
                ),
            ),
        )

    fun getAllIcons(): List<ProfileIcon> = categories.flatMap { it.icons }

    fun getIconById(id: String?): ImageVector? {
        if (id == null) return null
        return getAllIcons().find { it.id == id }?.icon
    }

    fun getCategoryForIcon(iconId: String): String? = categories.find { category ->
        category.icons.any { it.id == iconId }
    }?.name

    fun searchIcons(query: String): List<ProfileIcon> {
        val lowercaseQuery = query.lowercase()
        return getAllIcons().filter { icon ->
            icon.id.contains(lowercaseQuery) ||
                icon.label.lowercase().contains(lowercaseQuery)
        }
    }
}
